doctrine:
    dbal:
        default_connection: evisa
        connections:
            evisa:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL)%'
                charset: utf8mb4
                mapping_types:
                    enum: string
                    bit: integer
    orm:
        default_entity_manager: evisa
        entity_managers:
            evisa:
                connection: evisa
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Core:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: core
when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
