version: '3.6'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: satelite-list-app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /etc/localtime:/etc/localtime:ro

  nginx:
    image: nginx:1.19-alpine
    container_name: satelite-list-nginx
    restart: always
    ports:
      - 8006:86
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
