version: '3.6'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: workbench-app
    restart: always
    depends_on:
      - db
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/apache/vhosts:/etc/apache2/sites-enabled
      - /etc/localtime:/etc/localtime:ro
    networks:
      - satellite-network
    ports:
      - "8001:80"

  db:
    image: mysql:9
    restart: always
    container_name: workbench-mysql
    command:
      - --innodb-buffer-pool-size=512M
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: workbench
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    ports:
      - '3301:3306'
    networks:
      - satellite-network

#  nginx:
#    image: nginx:1.19-alpine
#    container_name: satellites-nginx
#    restart: always
#    ports:
#      - 8006:86
#    volumes:
#      - ./:/var/www/html
#      - ./docker/nginx:/etc/nginx/conf.d
#    networks:
#      - satellite-network

networks:
  satellite-network:
    name: docker_default
    external: true
