version: '3.6'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: satelite-list-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../app:/var/www/

  nginx:
    image: nginx:1.19-alpine
    container_name: satelite-list-nginx
    restart: always
    ports:
      - 8006:86
    volumes:
      - ../app:/var/www/
      - ./nginx:/etc/nginx/conf.d
