version: '3.6'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: ivs_mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --innodb-buffer-pool-size=1G
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: satellites
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
    networks:
      - satellite-network

networks:
  satellite-network:
    name: docker_default
    external: true

